### ISSUE TITLE
Help me update requirement plz

### ISSUE THREAD

**Issue by WaterSo0910** [big-data-project-group2/tweet-stock-prediction#2]
@Chr1sInTheHouse How can u freeze requirement if u don't have venv

**Comment by Chr1sInTheHouse** [comment]
under venv or your local environment:
- `pip install pip-tools`
- add new package into `requiements.in`
- run `pip-compile` in command line
- then new `requirements.txt` would be generated

**Comment by WaterSo0910** [comment]
So `requirements.in` should be included in `.gitignore` ?
And I don't have pip-compile command
